# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/markus/dev/ba_spheremarcher

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/markus/dev/ba_spheremarcher

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/markus/dev/ba_spheremarcher/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/markus/dev/ba_spheremarcher/CMakeFiles /home/markus/dev/ba_spheremarcher/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/markus/dev/ba_spheremarcher/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Spheremarcher

# Build rule for target.
Spheremarcher: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Spheremarcher
.PHONY : Spheremarcher

# fast build rule for target.
Spheremarcher/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/build
.PHONY : Spheremarcher/fast

#=============================================================================
# Target rules for targets named docs

# Build rule for target.
docs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 docs
.PHONY : docs

# fast build rule for target.
docs/fast:
	$(MAKE) $(MAKESILENT) -f docs/CMakeFiles/docs.dir/build.make docs/CMakeFiles/docs.dir/build
.PHONY : docs/fast

#=============================================================================
# Target rules for targets named doxygen

# Build rule for target.
doxygen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 doxygen
.PHONY : doxygen

# fast build rule for target.
doxygen/fast:
	$(MAKE) $(MAKESILENT) -f docs/CMakeFiles/doxygen.dir/build.make docs/CMakeFiles/doxygen.dir/build
.PHONY : doxygen/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f dependency/pmp-library/CMakeFiles/uninstall.dir/build.make dependency/pmp-library/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glew

# Build rule for target.
glew: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glew
.PHONY : glew

# fast build rule for target.
glew/fast:
	$(MAKE) $(MAKESILENT) -f dependency/pmp-library/CMakeFiles/glew.dir/build.make dependency/pmp-library/CMakeFiles/glew.dir/build
.PHONY : glew/fast

#=============================================================================
# Target rules for targets named stb_image

# Build rule for target.
stb_image: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stb_image
.PHONY : stb_image

# fast build rule for target.
stb_image/fast:
	$(MAKE) $(MAKESILENT) -f dependency/pmp-library/external/stb_image/CMakeFiles/stb_image.dir/build.make dependency/pmp-library/external/stb_image/CMakeFiles/stb_image.dir/build
.PHONY : stb_image/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f dependency/pmp-library/external/glew/src/CMakeFiles/glfw.dir/build.make dependency/pmp-library/external/glew/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f dependency/pmp-library/external/imgui/CMakeFiles/imgui.dir/build.make dependency/pmp-library/external/imgui/CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named rply

# Build rule for target.
rply: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rply
.PHONY : rply

# fast build rule for target.
rply/fast:
	$(MAKE) $(MAKESILENT) -f dependency/pmp-library/external/rply/CMakeFiles/rply.dir/build.make dependency/pmp-library/external/rply/CMakeFiles/rply.dir/build
.PHONY : rply/fast

#=============================================================================
# Target rules for targets named pmp

# Build rule for target.
pmp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pmp
.PHONY : pmp

# fast build rule for target.
pmp/fast:
	$(MAKE) $(MAKESILENT) -f dependency/pmp-library/src/pmp/CMakeFiles/pmp.dir/build.make dependency/pmp-library/src/pmp/CMakeFiles/pmp.dir/build
.PHONY : pmp/fast

#=============================================================================
# Target rules for targets named pmp_vis

# Build rule for target.
pmp_vis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pmp_vis
.PHONY : pmp_vis

# fast build rule for target.
pmp_vis/fast:
	$(MAKE) $(MAKESILENT) -f dependency/pmp-library/src/pmp/visualization/CMakeFiles/pmp_vis.dir/build.make dependency/pmp-library/src/pmp/visualization/CMakeFiles/pmp_vis.dir/build
.PHONY : pmp_vis/fast

dependency/pmp-library/external/imgui/imgui.o: dependency/pmp-library/external/imgui/imgui.cpp.o

.PHONY : dependency/pmp-library/external/imgui/imgui.o

# target to build an object file
dependency/pmp-library/external/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/pmp-library/external/imgui/imgui.cpp.o
.PHONY : dependency/pmp-library/external/imgui/imgui.cpp.o

dependency/pmp-library/external/imgui/imgui.i: dependency/pmp-library/external/imgui/imgui.cpp.i

.PHONY : dependency/pmp-library/external/imgui/imgui.i

# target to preprocess a source file
dependency/pmp-library/external/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/pmp-library/external/imgui/imgui.cpp.i
.PHONY : dependency/pmp-library/external/imgui/imgui.cpp.i

dependency/pmp-library/external/imgui/imgui.s: dependency/pmp-library/external/imgui/imgui.cpp.s

.PHONY : dependency/pmp-library/external/imgui/imgui.s

# target to generate assembly for a file
dependency/pmp-library/external/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/pmp-library/external/imgui/imgui.cpp.s
.PHONY : dependency/pmp-library/external/imgui/imgui.cpp.s

dependency/pmp-library/external/imgui/imgui_demo.o: dependency/pmp-library/external/imgui/imgui_demo.cpp.o

.PHONY : dependency/pmp-library/external/imgui/imgui_demo.o

# target to build an object file
dependency/pmp-library/external/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/pmp-library/external/imgui/imgui_demo.cpp.o
.PHONY : dependency/pmp-library/external/imgui/imgui_demo.cpp.o

dependency/pmp-library/external/imgui/imgui_demo.i: dependency/pmp-library/external/imgui/imgui_demo.cpp.i

.PHONY : dependency/pmp-library/external/imgui/imgui_demo.i

# target to preprocess a source file
dependency/pmp-library/external/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/pmp-library/external/imgui/imgui_demo.cpp.i
.PHONY : dependency/pmp-library/external/imgui/imgui_demo.cpp.i

dependency/pmp-library/external/imgui/imgui_demo.s: dependency/pmp-library/external/imgui/imgui_demo.cpp.s

.PHONY : dependency/pmp-library/external/imgui/imgui_demo.s

# target to generate assembly for a file
dependency/pmp-library/external/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/pmp-library/external/imgui/imgui_demo.cpp.s
.PHONY : dependency/pmp-library/external/imgui/imgui_demo.cpp.s

dependency/pmp-library/external/imgui/imgui_draw.o: dependency/pmp-library/external/imgui/imgui_draw.cpp.o

.PHONY : dependency/pmp-library/external/imgui/imgui_draw.o

# target to build an object file
dependency/pmp-library/external/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/pmp-library/external/imgui/imgui_draw.cpp.o
.PHONY : dependency/pmp-library/external/imgui/imgui_draw.cpp.o

dependency/pmp-library/external/imgui/imgui_draw.i: dependency/pmp-library/external/imgui/imgui_draw.cpp.i

.PHONY : dependency/pmp-library/external/imgui/imgui_draw.i

# target to preprocess a source file
dependency/pmp-library/external/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/pmp-library/external/imgui/imgui_draw.cpp.i
.PHONY : dependency/pmp-library/external/imgui/imgui_draw.cpp.i

dependency/pmp-library/external/imgui/imgui_draw.s: dependency/pmp-library/external/imgui/imgui_draw.cpp.s

.PHONY : dependency/pmp-library/external/imgui/imgui_draw.s

# target to generate assembly for a file
dependency/pmp-library/external/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/pmp-library/external/imgui/imgui_draw.cpp.s
.PHONY : dependency/pmp-library/external/imgui/imgui_draw.cpp.s

dependency/pmp-library/external/imgui/imgui_impl_glfw.o: dependency/pmp-library/external/imgui/imgui_impl_glfw.cpp.o

.PHONY : dependency/pmp-library/external/imgui/imgui_impl_glfw.o

# target to build an object file
dependency/pmp-library/external/imgui/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/pmp-library/external/imgui/imgui_impl_glfw.cpp.o
.PHONY : dependency/pmp-library/external/imgui/imgui_impl_glfw.cpp.o

dependency/pmp-library/external/imgui/imgui_impl_glfw.i: dependency/pmp-library/external/imgui/imgui_impl_glfw.cpp.i

.PHONY : dependency/pmp-library/external/imgui/imgui_impl_glfw.i

# target to preprocess a source file
dependency/pmp-library/external/imgui/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/pmp-library/external/imgui/imgui_impl_glfw.cpp.i
.PHONY : dependency/pmp-library/external/imgui/imgui_impl_glfw.cpp.i

dependency/pmp-library/external/imgui/imgui_impl_glfw.s: dependency/pmp-library/external/imgui/imgui_impl_glfw.cpp.s

.PHONY : dependency/pmp-library/external/imgui/imgui_impl_glfw.s

# target to generate assembly for a file
dependency/pmp-library/external/imgui/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/pmp-library/external/imgui/imgui_impl_glfw.cpp.s
.PHONY : dependency/pmp-library/external/imgui/imgui_impl_glfw.cpp.s

dependency/pmp-library/external/imgui/imgui_impl_opengl3.o: dependency/pmp-library/external/imgui/imgui_impl_opengl3.cpp.o

.PHONY : dependency/pmp-library/external/imgui/imgui_impl_opengl3.o

# target to build an object file
dependency/pmp-library/external/imgui/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/pmp-library/external/imgui/imgui_impl_opengl3.cpp.o
.PHONY : dependency/pmp-library/external/imgui/imgui_impl_opengl3.cpp.o

dependency/pmp-library/external/imgui/imgui_impl_opengl3.i: dependency/pmp-library/external/imgui/imgui_impl_opengl3.cpp.i

.PHONY : dependency/pmp-library/external/imgui/imgui_impl_opengl3.i

# target to preprocess a source file
dependency/pmp-library/external/imgui/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/pmp-library/external/imgui/imgui_impl_opengl3.cpp.i
.PHONY : dependency/pmp-library/external/imgui/imgui_impl_opengl3.cpp.i

dependency/pmp-library/external/imgui/imgui_impl_opengl3.s: dependency/pmp-library/external/imgui/imgui_impl_opengl3.cpp.s

.PHONY : dependency/pmp-library/external/imgui/imgui_impl_opengl3.s

# target to generate assembly for a file
dependency/pmp-library/external/imgui/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/pmp-library/external/imgui/imgui_impl_opengl3.cpp.s
.PHONY : dependency/pmp-library/external/imgui/imgui_impl_opengl3.cpp.s

dependency/pmp-library/external/imgui/imgui_widgets.o: dependency/pmp-library/external/imgui/imgui_widgets.cpp.o

.PHONY : dependency/pmp-library/external/imgui/imgui_widgets.o

# target to build an object file
dependency/pmp-library/external/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/pmp-library/external/imgui/imgui_widgets.cpp.o
.PHONY : dependency/pmp-library/external/imgui/imgui_widgets.cpp.o

dependency/pmp-library/external/imgui/imgui_widgets.i: dependency/pmp-library/external/imgui/imgui_widgets.cpp.i

.PHONY : dependency/pmp-library/external/imgui/imgui_widgets.i

# target to preprocess a source file
dependency/pmp-library/external/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/pmp-library/external/imgui/imgui_widgets.cpp.i
.PHONY : dependency/pmp-library/external/imgui/imgui_widgets.cpp.i

dependency/pmp-library/external/imgui/imgui_widgets.s: dependency/pmp-library/external/imgui/imgui_widgets.cpp.s

.PHONY : dependency/pmp-library/external/imgui/imgui_widgets.s

# target to generate assembly for a file
dependency/pmp-library/external/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/pmp-library/external/imgui/imgui_widgets.cpp.s
.PHONY : dependency/pmp-library/external/imgui/imgui_widgets.cpp.s

src/Spheremarcher.o: src/Spheremarcher.cpp.o

.PHONY : src/Spheremarcher.o

# target to build an object file
src/Spheremarcher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/Spheremarcher.cpp.o
.PHONY : src/Spheremarcher.cpp.o

src/Spheremarcher.i: src/Spheremarcher.cpp.i

.PHONY : src/Spheremarcher.i

# target to preprocess a source file
src/Spheremarcher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/Spheremarcher.cpp.i
.PHONY : src/Spheremarcher.cpp.i

src/Spheremarcher.s: src/Spheremarcher.cpp.s

.PHONY : src/Spheremarcher.s

# target to generate assembly for a file
src/Spheremarcher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/Spheremarcher.cpp.s
.PHONY : src/Spheremarcher.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils/Camera.o: src/utils/Camera.cpp.o

.PHONY : src/utils/Camera.o

# target to build an object file
src/utils/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/Camera.cpp.o
.PHONY : src/utils/Camera.cpp.o

src/utils/Camera.i: src/utils/Camera.cpp.i

.PHONY : src/utils/Camera.i

# target to preprocess a source file
src/utils/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/Camera.cpp.i
.PHONY : src/utils/Camera.cpp.i

src/utils/Camera.s: src/utils/Camera.cpp.s

.PHONY : src/utils/Camera.s

# target to generate assembly for a file
src/utils/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/Camera.cpp.s
.PHONY : src/utils/Camera.cpp.s

src/utils/FrameBuffer.o: src/utils/FrameBuffer.cpp.o

.PHONY : src/utils/FrameBuffer.o

# target to build an object file
src/utils/FrameBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/FrameBuffer.cpp.o
.PHONY : src/utils/FrameBuffer.cpp.o

src/utils/FrameBuffer.i: src/utils/FrameBuffer.cpp.i

.PHONY : src/utils/FrameBuffer.i

# target to preprocess a source file
src/utils/FrameBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/FrameBuffer.cpp.i
.PHONY : src/utils/FrameBuffer.cpp.i

src/utils/FrameBuffer.s: src/utils/FrameBuffer.cpp.s

.PHONY : src/utils/FrameBuffer.s

# target to generate assembly for a file
src/utils/FrameBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/FrameBuffer.cpp.s
.PHONY : src/utils/FrameBuffer.cpp.s

src/utils/SDFGenerator.o: src/utils/SDFGenerator.cpp.o

.PHONY : src/utils/SDFGenerator.o

# target to build an object file
src/utils/SDFGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/SDFGenerator.cpp.o
.PHONY : src/utils/SDFGenerator.cpp.o

src/utils/SDFGenerator.i: src/utils/SDFGenerator.cpp.i

.PHONY : src/utils/SDFGenerator.i

# target to preprocess a source file
src/utils/SDFGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/SDFGenerator.cpp.i
.PHONY : src/utils/SDFGenerator.cpp.i

src/utils/SDFGenerator.s: src/utils/SDFGenerator.cpp.s

.PHONY : src/utils/SDFGenerator.s

# target to generate assembly for a file
src/utils/SDFGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/SDFGenerator.cpp.s
.PHONY : src/utils/SDFGenerator.cpp.s

src/utils/SDField.o: src/utils/SDField.cpp.o

.PHONY : src/utils/SDField.o

# target to build an object file
src/utils/SDField.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/SDField.cpp.o
.PHONY : src/utils/SDField.cpp.o

src/utils/SDField.i: src/utils/SDField.cpp.i

.PHONY : src/utils/SDField.i

# target to preprocess a source file
src/utils/SDField.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/SDField.cpp.i
.PHONY : src/utils/SDField.cpp.i

src/utils/SDField.s: src/utils/SDField.cpp.s

.PHONY : src/utils/SDField.s

# target to generate assembly for a file
src/utils/SDField.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/SDField.cpp.s
.PHONY : src/utils/SDField.cpp.s

src/utils/Shader.o: src/utils/Shader.cpp.o

.PHONY : src/utils/Shader.o

# target to build an object file
src/utils/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/Shader.cpp.o
.PHONY : src/utils/Shader.cpp.o

src/utils/Shader.i: src/utils/Shader.cpp.i

.PHONY : src/utils/Shader.i

# target to preprocess a source file
src/utils/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/Shader.cpp.i
.PHONY : src/utils/Shader.cpp.i

src/utils/Shader.s: src/utils/Shader.cpp.s

.PHONY : src/utils/Shader.s

# target to generate assembly for a file
src/utils/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/Shader.cpp.s
.PHONY : src/utils/Shader.cpp.s

src/utils/TextureSampler.o: src/utils/TextureSampler.cpp.o

.PHONY : src/utils/TextureSampler.o

# target to build an object file
src/utils/TextureSampler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/TextureSampler.cpp.o
.PHONY : src/utils/TextureSampler.cpp.o

src/utils/TextureSampler.i: src/utils/TextureSampler.cpp.i

.PHONY : src/utils/TextureSampler.i

# target to preprocess a source file
src/utils/TextureSampler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/TextureSampler.cpp.i
.PHONY : src/utils/TextureSampler.cpp.i

src/utils/TextureSampler.s: src/utils/TextureSampler.cpp.s

.PHONY : src/utils/TextureSampler.s

# target to generate assembly for a file
src/utils/TextureSampler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/TextureSampler.cpp.s
.PHONY : src/utils/TextureSampler.cpp.s

src/utils/Window.o: src/utils/Window.cpp.o

.PHONY : src/utils/Window.o

# target to build an object file
src/utils/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/Window.cpp.o
.PHONY : src/utils/Window.cpp.o

src/utils/Window.i: src/utils/Window.cpp.i

.PHONY : src/utils/Window.i

# target to preprocess a source file
src/utils/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/Window.cpp.i
.PHONY : src/utils/Window.cpp.i

src/utils/Window.s: src/utils/Window.cpp.s

.PHONY : src/utils/Window.s

# target to generate assembly for a file
src/utils/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/Window.cpp.s
.PHONY : src/utils/Window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... docs"
	@echo "... doxygen"
	@echo "... uninstall"
	@echo "... Spheremarcher"
	@echo "... glew"
	@echo "... glfw"
	@echo "... imgui"
	@echo "... pmp"
	@echo "... pmp_vis"
	@echo "... rply"
	@echo "... stb_image"
	@echo "... dependency/pmp-library/external/imgui/imgui.o"
	@echo "... dependency/pmp-library/external/imgui/imgui.i"
	@echo "... dependency/pmp-library/external/imgui/imgui.s"
	@echo "... dependency/pmp-library/external/imgui/imgui_demo.o"
	@echo "... dependency/pmp-library/external/imgui/imgui_demo.i"
	@echo "... dependency/pmp-library/external/imgui/imgui_demo.s"
	@echo "... dependency/pmp-library/external/imgui/imgui_draw.o"
	@echo "... dependency/pmp-library/external/imgui/imgui_draw.i"
	@echo "... dependency/pmp-library/external/imgui/imgui_draw.s"
	@echo "... dependency/pmp-library/external/imgui/imgui_impl_glfw.o"
	@echo "... dependency/pmp-library/external/imgui/imgui_impl_glfw.i"
	@echo "... dependency/pmp-library/external/imgui/imgui_impl_glfw.s"
	@echo "... dependency/pmp-library/external/imgui/imgui_impl_opengl3.o"
	@echo "... dependency/pmp-library/external/imgui/imgui_impl_opengl3.i"
	@echo "... dependency/pmp-library/external/imgui/imgui_impl_opengl3.s"
	@echo "... dependency/pmp-library/external/imgui/imgui_widgets.o"
	@echo "... dependency/pmp-library/external/imgui/imgui_widgets.i"
	@echo "... dependency/pmp-library/external/imgui/imgui_widgets.s"
	@echo "... src/Spheremarcher.o"
	@echo "... src/Spheremarcher.i"
	@echo "... src/Spheremarcher.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils/Camera.o"
	@echo "... src/utils/Camera.i"
	@echo "... src/utils/Camera.s"
	@echo "... src/utils/FrameBuffer.o"
	@echo "... src/utils/FrameBuffer.i"
	@echo "... src/utils/FrameBuffer.s"
	@echo "... src/utils/SDFGenerator.o"
	@echo "... src/utils/SDFGenerator.i"
	@echo "... src/utils/SDFGenerator.s"
	@echo "... src/utils/SDField.o"
	@echo "... src/utils/SDField.i"
	@echo "... src/utils/SDField.s"
	@echo "... src/utils/Shader.o"
	@echo "... src/utils/Shader.i"
	@echo "... src/utils/Shader.s"
	@echo "... src/utils/TextureSampler.o"
	@echo "... src/utils/TextureSampler.i"
	@echo "... src/utils/TextureSampler.s"
	@echo "... src/utils/Window.o"
	@echo "... src/utils/Window.i"
	@echo "... src/utils/Window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

