# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/markus/dev/ba_spheremarcher

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/markus/dev/ba_spheremarcher

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/markus/dev/ba_spheremarcher/CMakeFiles /home/markus/dev/ba_spheremarcher/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/markus/dev/ba_spheremarcher/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Spheremarcher

# Build rule for target.
Spheremarcher: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Spheremarcher
.PHONY : Spheremarcher

# fast build rule for target.
Spheremarcher/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/build
.PHONY : Spheremarcher/fast

#=============================================================================
# Target rules for targets named glew_s

# Build rule for target.
glew_s: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glew_s
.PHONY : glew_s

# fast build rule for target.
glew_s/fast:
	$(MAKE) $(MAKESILENT) -f dependency/glew/build/cmake/CMakeFiles/glew_s.dir/build.make dependency/glew/build/cmake/CMakeFiles/glew_s.dir/build
.PHONY : glew_s/fast

#=============================================================================
# Target rules for targets named visualinfo

# Build rule for target.
visualinfo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 visualinfo
.PHONY : visualinfo

# fast build rule for target.
visualinfo/fast:
	$(MAKE) $(MAKESILENT) -f dependency/glew/build/cmake/CMakeFiles/visualinfo.dir/build.make dependency/glew/build/cmake/CMakeFiles/visualinfo.dir/build
.PHONY : visualinfo/fast

#=============================================================================
# Target rules for targets named glew

# Build rule for target.
glew: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glew
.PHONY : glew

# fast build rule for target.
glew/fast:
	$(MAKE) $(MAKESILENT) -f dependency/glew/build/cmake/CMakeFiles/glew.dir/build.make dependency/glew/build/cmake/CMakeFiles/glew.dir/build
.PHONY : glew/fast

#=============================================================================
# Target rules for targets named glewinfo

# Build rule for target.
glewinfo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glewinfo
.PHONY : glewinfo

# fast build rule for target.
glewinfo/fast:
	$(MAKE) $(MAKESILENT) -f dependency/glew/build/cmake/CMakeFiles/glewinfo.dir/build.make dependency/glew/build/cmake/CMakeFiles/glewinfo.dir/build
.PHONY : glewinfo/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f dependency/glew/build/cmake/CMakeFiles/uninstall.dir/build.make dependency/glew/build/cmake/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f dependency/glfw/src/CMakeFiles/glfw.dir/build.make dependency/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

dependency/imgui/imgui.o: dependency/imgui/imgui.cpp.o

.PHONY : dependency/imgui/imgui.o

# target to build an object file
dependency/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/imgui/imgui.cpp.o
.PHONY : dependency/imgui/imgui.cpp.o

dependency/imgui/imgui.i: dependency/imgui/imgui.cpp.i

.PHONY : dependency/imgui/imgui.i

# target to preprocess a source file
dependency/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/imgui/imgui.cpp.i
.PHONY : dependency/imgui/imgui.cpp.i

dependency/imgui/imgui.s: dependency/imgui/imgui.cpp.s

.PHONY : dependency/imgui/imgui.s

# target to generate assembly for a file
dependency/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/imgui/imgui.cpp.s
.PHONY : dependency/imgui/imgui.cpp.s

dependency/imgui/imgui_demo.o: dependency/imgui/imgui_demo.cpp.o

.PHONY : dependency/imgui/imgui_demo.o

# target to build an object file
dependency/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/imgui/imgui_demo.cpp.o
.PHONY : dependency/imgui/imgui_demo.cpp.o

dependency/imgui/imgui_demo.i: dependency/imgui/imgui_demo.cpp.i

.PHONY : dependency/imgui/imgui_demo.i

# target to preprocess a source file
dependency/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/imgui/imgui_demo.cpp.i
.PHONY : dependency/imgui/imgui_demo.cpp.i

dependency/imgui/imgui_demo.s: dependency/imgui/imgui_demo.cpp.s

.PHONY : dependency/imgui/imgui_demo.s

# target to generate assembly for a file
dependency/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/imgui/imgui_demo.cpp.s
.PHONY : dependency/imgui/imgui_demo.cpp.s

dependency/imgui/imgui_draw.o: dependency/imgui/imgui_draw.cpp.o

.PHONY : dependency/imgui/imgui_draw.o

# target to build an object file
dependency/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/imgui/imgui_draw.cpp.o
.PHONY : dependency/imgui/imgui_draw.cpp.o

dependency/imgui/imgui_draw.i: dependency/imgui/imgui_draw.cpp.i

.PHONY : dependency/imgui/imgui_draw.i

# target to preprocess a source file
dependency/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/imgui/imgui_draw.cpp.i
.PHONY : dependency/imgui/imgui_draw.cpp.i

dependency/imgui/imgui_draw.s: dependency/imgui/imgui_draw.cpp.s

.PHONY : dependency/imgui/imgui_draw.s

# target to generate assembly for a file
dependency/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/imgui/imgui_draw.cpp.s
.PHONY : dependency/imgui/imgui_draw.cpp.s

dependency/imgui/imgui_impl_glfw.o: dependency/imgui/imgui_impl_glfw.cpp.o

.PHONY : dependency/imgui/imgui_impl_glfw.o

# target to build an object file
dependency/imgui/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/imgui/imgui_impl_glfw.cpp.o
.PHONY : dependency/imgui/imgui_impl_glfw.cpp.o

dependency/imgui/imgui_impl_glfw.i: dependency/imgui/imgui_impl_glfw.cpp.i

.PHONY : dependency/imgui/imgui_impl_glfw.i

# target to preprocess a source file
dependency/imgui/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/imgui/imgui_impl_glfw.cpp.i
.PHONY : dependency/imgui/imgui_impl_glfw.cpp.i

dependency/imgui/imgui_impl_glfw.s: dependency/imgui/imgui_impl_glfw.cpp.s

.PHONY : dependency/imgui/imgui_impl_glfw.s

# target to generate assembly for a file
dependency/imgui/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/imgui/imgui_impl_glfw.cpp.s
.PHONY : dependency/imgui/imgui_impl_glfw.cpp.s

dependency/imgui/imgui_impl_opengl3.o: dependency/imgui/imgui_impl_opengl3.cpp.o

.PHONY : dependency/imgui/imgui_impl_opengl3.o

# target to build an object file
dependency/imgui/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/imgui/imgui_impl_opengl3.cpp.o
.PHONY : dependency/imgui/imgui_impl_opengl3.cpp.o

dependency/imgui/imgui_impl_opengl3.i: dependency/imgui/imgui_impl_opengl3.cpp.i

.PHONY : dependency/imgui/imgui_impl_opengl3.i

# target to preprocess a source file
dependency/imgui/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/imgui/imgui_impl_opengl3.cpp.i
.PHONY : dependency/imgui/imgui_impl_opengl3.cpp.i

dependency/imgui/imgui_impl_opengl3.s: dependency/imgui/imgui_impl_opengl3.cpp.s

.PHONY : dependency/imgui/imgui_impl_opengl3.s

# target to generate assembly for a file
dependency/imgui/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/imgui/imgui_impl_opengl3.cpp.s
.PHONY : dependency/imgui/imgui_impl_opengl3.cpp.s

dependency/imgui/imgui_widgets.o: dependency/imgui/imgui_widgets.cpp.o

.PHONY : dependency/imgui/imgui_widgets.o

# target to build an object file
dependency/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/imgui/imgui_widgets.cpp.o
.PHONY : dependency/imgui/imgui_widgets.cpp.o

dependency/imgui/imgui_widgets.i: dependency/imgui/imgui_widgets.cpp.i

.PHONY : dependency/imgui/imgui_widgets.i

# target to preprocess a source file
dependency/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/imgui/imgui_widgets.cpp.i
.PHONY : dependency/imgui/imgui_widgets.cpp.i

dependency/imgui/imgui_widgets.s: dependency/imgui/imgui_widgets.cpp.s

.PHONY : dependency/imgui/imgui_widgets.s

# target to generate assembly for a file
dependency/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/dependency/imgui/imgui_widgets.cpp.s
.PHONY : dependency/imgui/imgui_widgets.cpp.s

src/Spheremarcher.o: src/Spheremarcher.cpp.o

.PHONY : src/Spheremarcher.o

# target to build an object file
src/Spheremarcher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/Spheremarcher.cpp.o
.PHONY : src/Spheremarcher.cpp.o

src/Spheremarcher.i: src/Spheremarcher.cpp.i

.PHONY : src/Spheremarcher.i

# target to preprocess a source file
src/Spheremarcher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/Spheremarcher.cpp.i
.PHONY : src/Spheremarcher.cpp.i

src/Spheremarcher.s: src/Spheremarcher.cpp.s

.PHONY : src/Spheremarcher.s

# target to generate assembly for a file
src/Spheremarcher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/Spheremarcher.cpp.s
.PHONY : src/Spheremarcher.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils/Application.o: src/utils/Application.cpp.o

.PHONY : src/utils/Application.o

# target to build an object file
src/utils/Application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/Application.cpp.o
.PHONY : src/utils/Application.cpp.o

src/utils/Application.i: src/utils/Application.cpp.i

.PHONY : src/utils/Application.i

# target to preprocess a source file
src/utils/Application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/Application.cpp.i
.PHONY : src/utils/Application.cpp.i

src/utils/Application.s: src/utils/Application.cpp.s

.PHONY : src/utils/Application.s

# target to generate assembly for a file
src/utils/Application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/Application.cpp.s
.PHONY : src/utils/Application.cpp.s

src/utils/Camera.o: src/utils/Camera.cpp.o

.PHONY : src/utils/Camera.o

# target to build an object file
src/utils/Camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/Camera.cpp.o
.PHONY : src/utils/Camera.cpp.o

src/utils/Camera.i: src/utils/Camera.cpp.i

.PHONY : src/utils/Camera.i

# target to preprocess a source file
src/utils/Camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/Camera.cpp.i
.PHONY : src/utils/Camera.cpp.i

src/utils/Camera.s: src/utils/Camera.cpp.s

.PHONY : src/utils/Camera.s

# target to generate assembly for a file
src/utils/Camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/Camera.cpp.s
.PHONY : src/utils/Camera.cpp.s

src/utils/FrameBuffer.o: src/utils/FrameBuffer.cpp.o

.PHONY : src/utils/FrameBuffer.o

# target to build an object file
src/utils/FrameBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/FrameBuffer.cpp.o
.PHONY : src/utils/FrameBuffer.cpp.o

src/utils/FrameBuffer.i: src/utils/FrameBuffer.cpp.i

.PHONY : src/utils/FrameBuffer.i

# target to preprocess a source file
src/utils/FrameBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/FrameBuffer.cpp.i
.PHONY : src/utils/FrameBuffer.cpp.i

src/utils/FrameBuffer.s: src/utils/FrameBuffer.cpp.s

.PHONY : src/utils/FrameBuffer.s

# target to generate assembly for a file
src/utils/FrameBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/FrameBuffer.cpp.s
.PHONY : src/utils/FrameBuffer.cpp.s

src/utils/Material.o: src/utils/Material.cpp.o

.PHONY : src/utils/Material.o

# target to build an object file
src/utils/Material.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/Material.cpp.o
.PHONY : src/utils/Material.cpp.o

src/utils/Material.i: src/utils/Material.cpp.i

.PHONY : src/utils/Material.i

# target to preprocess a source file
src/utils/Material.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/Material.cpp.i
.PHONY : src/utils/Material.cpp.i

src/utils/Material.s: src/utils/Material.cpp.s

.PHONY : src/utils/Material.s

# target to generate assembly for a file
src/utils/Material.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/Material.cpp.s
.PHONY : src/utils/Material.cpp.s

src/utils/PrimitiveScene.o: src/utils/PrimitiveScene.cpp.o

.PHONY : src/utils/PrimitiveScene.o

# target to build an object file
src/utils/PrimitiveScene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/PrimitiveScene.cpp.o
.PHONY : src/utils/PrimitiveScene.cpp.o

src/utils/PrimitiveScene.i: src/utils/PrimitiveScene.cpp.i

.PHONY : src/utils/PrimitiveScene.i

# target to preprocess a source file
src/utils/PrimitiveScene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/PrimitiveScene.cpp.i
.PHONY : src/utils/PrimitiveScene.cpp.i

src/utils/PrimitiveScene.s: src/utils/PrimitiveScene.cpp.s

.PHONY : src/utils/PrimitiveScene.s

# target to generate assembly for a file
src/utils/PrimitiveScene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/PrimitiveScene.cpp.s
.PHONY : src/utils/PrimitiveScene.cpp.s

src/utils/SDFGenerator.o: src/utils/SDFGenerator.cpp.o

.PHONY : src/utils/SDFGenerator.o

# target to build an object file
src/utils/SDFGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/SDFGenerator.cpp.o
.PHONY : src/utils/SDFGenerator.cpp.o

src/utils/SDFGenerator.i: src/utils/SDFGenerator.cpp.i

.PHONY : src/utils/SDFGenerator.i

# target to preprocess a source file
src/utils/SDFGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/SDFGenerator.cpp.i
.PHONY : src/utils/SDFGenerator.cpp.i

src/utils/SDFGenerator.s: src/utils/SDFGenerator.cpp.s

.PHONY : src/utils/SDFGenerator.s

# target to generate assembly for a file
src/utils/SDFGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/SDFGenerator.cpp.s
.PHONY : src/utils/SDFGenerator.cpp.s

src/utils/Shader.o: src/utils/Shader.cpp.o

.PHONY : src/utils/Shader.o

# target to build an object file
src/utils/Shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/Shader.cpp.o
.PHONY : src/utils/Shader.cpp.o

src/utils/Shader.i: src/utils/Shader.cpp.i

.PHONY : src/utils/Shader.i

# target to preprocess a source file
src/utils/Shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/Shader.cpp.i
.PHONY : src/utils/Shader.cpp.i

src/utils/Shader.s: src/utils/Shader.cpp.s

.PHONY : src/utils/Shader.s

# target to generate assembly for a file
src/utils/Shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/Shader.cpp.s
.PHONY : src/utils/Shader.cpp.s

src/utils/TextureSampler.o: src/utils/TextureSampler.cpp.o

.PHONY : src/utils/TextureSampler.o

# target to build an object file
src/utils/TextureSampler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/TextureSampler.cpp.o
.PHONY : src/utils/TextureSampler.cpp.o

src/utils/TextureSampler.i: src/utils/TextureSampler.cpp.i

.PHONY : src/utils/TextureSampler.i

# target to preprocess a source file
src/utils/TextureSampler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/TextureSampler.cpp.i
.PHONY : src/utils/TextureSampler.cpp.i

src/utils/TextureSampler.s: src/utils/TextureSampler.cpp.s

.PHONY : src/utils/TextureSampler.s

# target to generate assembly for a file
src/utils/TextureSampler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/TextureSampler.cpp.s
.PHONY : src/utils/TextureSampler.cpp.s

src/utils/Window.o: src/utils/Window.cpp.o

.PHONY : src/utils/Window.o

# target to build an object file
src/utils/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/Window.cpp.o
.PHONY : src/utils/Window.cpp.o

src/utils/Window.i: src/utils/Window.cpp.i

.PHONY : src/utils/Window.i

# target to preprocess a source file
src/utils/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/Window.cpp.i
.PHONY : src/utils/Window.cpp.i

src/utils/Window.s: src/utils/Window.cpp.s

.PHONY : src/utils/Window.s

# target to generate assembly for a file
src/utils/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/Window.cpp.s
.PHONY : src/utils/Window.cpp.s

src/utils/raytracing/Mesh.o: src/utils/raytracing/Mesh.cpp.o

.PHONY : src/utils/raytracing/Mesh.o

# target to build an object file
src/utils/raytracing/Mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/raytracing/Mesh.cpp.o
.PHONY : src/utils/raytracing/Mesh.cpp.o

src/utils/raytracing/Mesh.i: src/utils/raytracing/Mesh.cpp.i

.PHONY : src/utils/raytracing/Mesh.i

# target to preprocess a source file
src/utils/raytracing/Mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/raytracing/Mesh.cpp.i
.PHONY : src/utils/raytracing/Mesh.cpp.i

src/utils/raytracing/Mesh.s: src/utils/raytracing/Mesh.cpp.s

.PHONY : src/utils/raytracing/Mesh.s

# target to generate assembly for a file
src/utils/raytracing/Mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Spheremarcher.dir/build.make CMakeFiles/Spheremarcher.dir/src/utils/raytracing/Mesh.cpp.s
.PHONY : src/utils/raytracing/Mesh.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... Spheremarcher"
	@echo "... glew"
	@echo "... glew_s"
	@echo "... glewinfo"
	@echo "... glfw"
	@echo "... visualinfo"
	@echo "... dependency/imgui/imgui.o"
	@echo "... dependency/imgui/imgui.i"
	@echo "... dependency/imgui/imgui.s"
	@echo "... dependency/imgui/imgui_demo.o"
	@echo "... dependency/imgui/imgui_demo.i"
	@echo "... dependency/imgui/imgui_demo.s"
	@echo "... dependency/imgui/imgui_draw.o"
	@echo "... dependency/imgui/imgui_draw.i"
	@echo "... dependency/imgui/imgui_draw.s"
	@echo "... dependency/imgui/imgui_impl_glfw.o"
	@echo "... dependency/imgui/imgui_impl_glfw.i"
	@echo "... dependency/imgui/imgui_impl_glfw.s"
	@echo "... dependency/imgui/imgui_impl_opengl3.o"
	@echo "... dependency/imgui/imgui_impl_opengl3.i"
	@echo "... dependency/imgui/imgui_impl_opengl3.s"
	@echo "... dependency/imgui/imgui_widgets.o"
	@echo "... dependency/imgui/imgui_widgets.i"
	@echo "... dependency/imgui/imgui_widgets.s"
	@echo "... src/Spheremarcher.o"
	@echo "... src/Spheremarcher.i"
	@echo "... src/Spheremarcher.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils/Application.o"
	@echo "... src/utils/Application.i"
	@echo "... src/utils/Application.s"
	@echo "... src/utils/Camera.o"
	@echo "... src/utils/Camera.i"
	@echo "... src/utils/Camera.s"
	@echo "... src/utils/FrameBuffer.o"
	@echo "... src/utils/FrameBuffer.i"
	@echo "... src/utils/FrameBuffer.s"
	@echo "... src/utils/Material.o"
	@echo "... src/utils/Material.i"
	@echo "... src/utils/Material.s"
	@echo "... src/utils/PrimitiveScene.o"
	@echo "... src/utils/PrimitiveScene.i"
	@echo "... src/utils/PrimitiveScene.s"
	@echo "... src/utils/SDFGenerator.o"
	@echo "... src/utils/SDFGenerator.i"
	@echo "... src/utils/SDFGenerator.s"
	@echo "... src/utils/Shader.o"
	@echo "... src/utils/Shader.i"
	@echo "... src/utils/Shader.s"
	@echo "... src/utils/TextureSampler.o"
	@echo "... src/utils/TextureSampler.i"
	@echo "... src/utils/TextureSampler.s"
	@echo "... src/utils/Window.o"
	@echo "... src/utils/Window.i"
	@echo "... src/utils/Window.s"
	@echo "... src/utils/raytracing/Mesh.o"
	@echo "... src/utils/raytracing/Mesh.i"
	@echo "... src/utils/raytracing/Mesh.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

